name: Songkkaa Building & deploying
on: [push]
env:
  IMAGENAME: 'songkkaa-backend'

jobs:
  Deploy-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: docker build -t $IMAGENAME backend/
        
      - name: Create network if not exists
        run: docker network create --driver bridge songkkaa_network || true
        
      - name: Undeploy old version
        run: docker stop songkkaa-backend || true && docker rm songkkaa-backend || true
        
      - name: Deploy new version
        run: docker run -d --name songkkaa-backend --network songkkaa_network --network nginx-expose --restart unless-stopped -v /opt/songkkaa/data.json:/app/data.json $IMAGENAME
        
      - name: Finished!
        run: echo "🍏 This job's status is ${{ job.status }}."
