name: Songkkaa Building & deploying
on: [push]
env:
  IMAGENAME: 'songkkaa'

jobs:
  Explore-Gitea-Actions:
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: docker build -t $IMAGENAME .
        name: Build Docker image
      - name: Create network if not exists
        run: docker network create --driver bridge eve_default || true
      - run: docker stop eve || true && docker rm eve || true
        name: Undeploy
      - run: docker run -d --name eve --network eve_default --restart unless-stopped -v /opt/bot/user.json:/bot/user.json ${IMAGENAME}
        name: Deploy
      - run: echo "🍏 This job's status is ${{ job.status }}."
        name: Finished!
